In [10]:
import pickle

with open('细胞系.pkl', 'rb') as file:
    cell_dict_W = pickle.load(file)
    cell_dict_columns = pickle.load(file)
    cell_dict_high_lines = pickle.load(file)

In [11]:
with open('药物对.pkl', 'rb') as file:
    drug_dict_W = pickle.load(file)
    drug_dict_columns = pickle.load(file)
    drug_dict_high_lines = pickle.load(file)

In [12]:
import numpy as np
import pandas as pd
import re,math
from sklearn import preprocessing
from scipy.stats import pearsonr
import matplotlib.pyplot as plt


data1 = pd.read_excel(r'pcbi.1006752.s002.xlsx', sheet_name="Sheet1",index_col='Drug').drop('SMILES',axis=1)
data2 = pd.read_excel(r'Label_synergy4000.xlsx')
data2_columns = data2.columns[2:]

In [13]:
# 结构  {名字： 名字列表， 权重： 权重列表} 顺序对应
dict_molecule_cell = {}
for elem in cell_dict_high_lines:
    dict_molecule_cell[elem] = []
    dict_molecule_cell[elem].append(cell_dict_columns[elem]["max_relevance"][-5:])
    dict_molecule_cell[elem].append(cell_dict_W[elem][-5:])

In [14]:
dict_molecule_drug = {}
for elem in drug_dict_high_lines:
    dict_molecule_drug[elem] = []
    dict_molecule_drug[elem].append(drug_dict_columns[elem]["max_relevance"][-5:])
    dict_molecule_drug[elem].append(drug_dict_W[elem][-5:])

In [15]:
# 拆分索引获取每行对应的drugA和drugB
drugA = []
drugB = []
for i in dict_molecule_drug:
    drugA.append(i.split(", ")[0][1:-1])
    drugB.append(i.split(", ")[1][1:-1])

In [16]:
# 原始数据中删除药物对得分低于0.90的行
temp = []
for index,row in data2.iterrows():
    status = 0
    for i,j in zip(drugA, drugB):
        if i == row[0] and j == row[1]:
            status = 1
    if status == 1:
        temp.append(row)
data22 = pd.DataFrame(temp)

In [17]:
# 获取得分高的细胞系名称组
cells = []
for i in dict_molecule_cell:
    cells.append(i)
cells.extend(data22.columns[0:2])

In [18]:
# 从原始数据中按列取得分高的细胞系
temp = []
for column,line in data22.iteritems():
    if column in cells:
        temp.append(line)
data222 = pd.DataFrame(temp).T

In [19]:
# 筛选结果合并drugA和drugB
tptt = []
for i,j in zip(data222['DrugA'], data222['DrugB']):
    tptt.append(f"'{i}', '{j}'")
data222 = pd.DataFrame(data222.iloc[:,2:].values,index=tptt,columns=data222.columns[2:])

In [20]:
# 原始数据合并drugA和drugB
tptt = []
for i,j in zip(data2['DrugA'], data2['DrugB']):
    tptt.append(f"'{i}', '{j}'")
data3 = pd.DataFrame(data2.iloc[:,2:].values,index=tptt,columns=data2.columns[2:])
data2 = data3.copy()

In [21]:
dict_molecule_cell

{'A2058_SKIN ': [Index(['MDAMB436_BREAST ', 'HT144_SKIN ', 'SKMEL30_SKIN ', 'UACC62_SKIN ',
         'NCIH460_LUNG '],
        dtype='object'),
  array([0.09100395, 0.13110556, 0.14273595, 0.1779505 , 0.22311708])],
 'A2780_OVARY ': [Index(['CAOV3_OVARY ', 'SW620_LARGE_INTESTINE ', 'A2058_SKIN ',
         'VCAP_PROSTATE ', 'COLO320_LARGE_INTESTINE '],
        dtype='object'),
  array([0.07210755, 0.07467228, 0.08339976, 0.22259993, 0.4901396 ])],
 'A375_SKIN ': [Index(['RKO_LARGE_INTESTINE ', 'UACC62_SKIN ', 'MSTO211H_PLEURA ',
         'A2058_SKIN ', 'HT144_SKIN '],
        dtype='object'),
  array([8.68755808e-05, 2.59003372e-04, 1.30224377e-03, 2.43787509e-03,
         6.17920176e-02])],
 'A427_LUNG ': [Index(['COLO320_LARGE_INTESTINE ', 'CAOV3_OVARY ', 'A2780_OVARY ',
         'T47D_BREAST ', 'NCIH23_LUNG '],
        dtype='object'),
  array([0.00152058, 0.00189082, 0.01278501, 0.01666771, 0.12073434])],
 'CAOV3_OVARY ': [Index(['SW837_LARGE_INTESTINE ', 'A2058_SKIN ', 'A2780_OVARY

In [22]:
# 预测筛选后的药物对与细胞系的协同得分
result_df = []
for i in data222.index:
    tp = []
    for k in data222.columns[0:]:
        molecule = 0
        denominator = 0
        a = dict_molecule_cell[k][0]
        b = dict_molecule_drug[i][0]
        cw = dict_molecule_cell[k][1]
        dw = dict_molecule_drug[i][1]
        for m,ccw in zip(a,cw): # 细胞系   名字  权重
            for n,ddw in zip(b,dw): # 药物对   名字   权重
                # 分子子项 = 细胞系权重 × data2对应名字的值 ×药物对权重
                temp_molecule = ccw*data2[data2.index==n][m].values[0]*ddw
                # 分母子项 = 细胞系权重 × 药物对权重
                temp_denominator = ccw*ddw
                molecule += temp_molecule
                denominator += temp_denominator
        result = molecule / denominator
        tp.append(result)
    result_df.append(tp)

In [23]:
sens=pd.DataFrame(np.array(result_df),index = data222.index, columns=data222.columns)

In [24]:
sens

A2058_SKIN   A2780_OVARY   A375_SKIN   \
'MK-5108', 'SORAFENIB'                 2.792456      5.442933   -0.474828   
'VINORELBINE', 'SUNITINIB'            -1.162660      6.508431    4.314476   
'SUNITINIB', 'MK-8776'                 1.778296      6.485968   -0.313071   
'5-FU', 'DINACICLIB'                  -3.693211     -0.135308  -14.218138   
'SUNITINIB', 'MK-2206'                 7.655789     10.218698    2.884418   
'PACLITAXEL', 'BEZ-235'               14.946517      7.139877   13.032786   
'MK-2206', 'DINACICLIB'               -3.198767      3.766895  -40.078484   
'MK-4827', 'MK-8776'                  -4.906098     10.250538  -43.189118   
'VINORELBINE', 'DINACICLIB'           -7.007000     -2.466188   -9.051505   
'MK-5108', 'MK-8776'                   7.558850      0.274629   -3.063444   
'TEMOZOLOMIDE', 'SN-38'                3.375108      6.816669    3.726401   
'ETOPOSIDE', 'MK-8669'                16.195657     10.675756   26.539209   
'SUNITINIB', 'MK-4827'                11.614865     13.430658    9.617690   
'BORTEZOMIB', 'GELDANAMYCIN'          -9.207401    -12.012882   -8.227644   
'PACLITAXEL', 'ABT-888'                4.368044      4.295320   -2.847430   
'CYCLOPHOSPHAMIDE', 'BEZ-235'          6.813819      6.818954    4.804218   
'DASATINIB', 'DINACICLIB'             -0.024000      5.422345  -11.501022   
'METHOTREXATE', 'ERLOTINIB'          -10.519781     -7.024851   -0.275281   
'MK-2206', 'TOPOTECAN'                19.841338     14.692574   26.102844   
'AZD1775', 'MK-4827'                  15.849619     11.615207   18.399240   
'METFORMIN', 'BEZ-235'                -2.720012     12.401163    3.040651   
'ZOLINZA', 'AZD1775'                   0.773051     -2.917593    7.937815   
'DASATINIB', 'SORAFENIB'               7.952314     16.502064  -21.633871   
'CYCLOPHOSPHAMIDE', 'TEMOZOLOMIDE'     9.358532      9.753714   12.203192   
'MRK-003', 'PACLITAXEL'                7.873652     17.020043   11.912076   
'DEXAMETHASONE', 'LAPATINIB'          10.656798     11.997293   15.267314   
'DEXAMETHASONE', 'MK-8669'             6.420333      7.019376   -0.502991   
'ERLOTINIB', 'BEZ-235'                13.215069     13.560135   10.819514   
'VINBLASTINE', 'PD325901'              5.364983     -6.730625   22.861829   
'MK-4541', 'METFORMIN'                 0.251104      7.879776   -6.255785   
...                                         ...           ...         ...   
'ETOPOSIDE', 'MK-2206'                24.305435     17.360218   28.618108   
'ETOPOSIDE', 'MK-4827'                 6.510786      9.122214    5.217880   
'LAPATINIB', 'MK-4827'                 4.281936      7.985409    8.047097   
'MRK-003', 'ERLOTINIB'                19.594015     10.598598   22.099112   
'ERLOTINIB', 'DASATINIB'               0.768114     11.080546  -26.080089   
'PACLITAXEL', 'GELDANAMYCIN'          -2.189368      7.667038   -0.593278   
'5-FU', 'L778123'                      5.890757      4.603513    4.861840   
'ERLOTINIB', 'MK-8776'                 9.923047     13.876469   11.665661   
'MITOMYCINE', 'L778123'                3.774163     10.248124   -6.051979   
'AZD1775', 'MK-8669'                  22.533779     13.491379   29.260490   
'L778123', 'LAPATINIB'                14.481531     10.005501    8.962815   
'MRK-003', 'AZD1775'                   9.858267     21.816258    2.846282   
'MK-4541', 'CYCLOPHOSPHAMIDE'          7.565213      8.410209    1.379978   
'ETOPOSIDE', 'MK-8776'                12.501337     17.643578   14.416101   
'METFORMIN', 'MK-4827'                13.747172      9.754294   15.457393   
'CYCLOPHOSPHAMIDE', 'ERLOTINIB'       -4.277807      8.142862   -3.595437   
'ZOLINZA', 'MK-2206'                  13.457657     16.303358    9.149943   
'VINBLASTINE', 'MK-8669'              12.090636      5.693580   17.468172   
'PD325901', 'OXALIPLATIN'             -1.115799      5.412825   -7.341639   
'MK-4541', '5-FU'                      7.350431      7.388685    1.678861   
'BORTEZOMIB', 'TOPOTECAN'       

In [25]:
MSE=pow(data222-sens,2).sum().sum()/(sens.shape[0]*sens.shape[1])
MSE

575.1169151942842