In [1]:
import re,math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from scipy.stats import pearsonr
from scipy.optimize import leastsq


data1 = pd.read_csv(r'细胞间相似性（皮尔森）.csv',engine='python')
# 细胞系-细胞系
high_data = data1.set_index(data1.loc[:,"Unnamed: 0"]).drop(["Unnamed: 0"], axis=1)
# 药物对-细胞系
data2 = pd.read_csv('label_gai.csv')
# 选取细胞系名称
columns = list(data2.columns[1:])
# 删去对应行后的字典
dict_high_lines = {}
count = 0
for i in high_data.index:
    y = list(high_data.loc[:,i])
    y.pop(count)
    count += 1  
    dict_high_lines[i] = y
# 分离x y数据构造字典
dict_columns = {}
for i in columns: 
    
    # b
    y = data2.loc[:,i]
    
    # A
    temp = []
    for j in columns:
        if j != i:
            temp.append(j)
    m = data2.loc[:, temp[0]]
    tp = [m]
    for j in temp[1:]:
        tp.append(data2.loc[:, j])
    x = pd.DataFrame(tp).T
    
    tp = []
    for j in columns:
        if i != j:
            tp.append(j)
    df = pd.DataFrame(dict_high_lines[i], index=tp)
    df.sort_values(by=0 , inplace=True, ascending=True)
    max_l = df.index[-13:]
    tp = []
    for j in max_l:
        tp.append(data2.loc[:, j])
    max_5x = pd.DataFrame(tp).T
    
    # 存储
    data = {
        "x": x,
        "y": y,
        "max_relevance": max_l,
        "max_5x": max_5x
    }
    dict_columns[i] = data
# 删去对应行后的字典
dict_high_lines = {}
count = 0
for i in high_data.index:
    y = list(high_data.loc[:,i])
    y.pop(count)
    count += 1
    dict_high_lines[i] = y

    tp = []
    for j in columns:
        if i != j:
            tp.append(j)
    df = pd.DataFrame(dict_high_lines[i], index=tp)
    df.sort_values(by=0 , inplace=True, ascending=True)
    
    max_l = df.index[-5:] 
    tp = []
    for j in max_l:
        tp.append(high_data.loc[j, :])
    max_5y = list(pd.DataFrame(tp).T.loc[[i]].values)[0]
    
    data = {
        "max_relevance": max_l,
        "y": y,
        "high_5": max_5y
    }
    dict_high_lines[i] = data

cell_dict_columns=dict_columns
cell_dict_high_lines=dict_high_lines

In [2]:
data1 = pd.read_excel(r'pcbi.1006752.s002.xlsx', sheet_name="Sheet1",index_col='Drug').drop('SMILES',axis=1)
data2 = pd.read_excel(r'Label_synergy4000.xlsx')
# 合并drugA和drugB为一列作为索引
temp1 = []
index_l = []
for index,row in data2.iterrows():
    ct = np.array(data1.loc[row["DrugA"],:]) + np.array(data1.loc[row["DrugB"],:])
    tp = []
    for i in ct:
        if i >= 1:
            tp.append(1)
        else:
            tp.append(0)
    temp1.append(tp)
    index_l.append((row["DrugA"],row["DrugB"]))
# 两组数据的tanimoto计算
def tanimoto(p,q):
    tep1=0
    tep2=0
    lenthp=int(len(p))
    for i in range(lenthp):
        a=p[i]        
        b=q[i]
        if (a==1)|(b==1):
            tep1=tep1+1
        if (a==1)&(b==1):
            tep2=tep2+1 
    c=float(tep2 / tep1)        
    return c
# 相互之间做一次tanimoto
temp=[]  
for i in temp1:
    tmp=[]   
    a=np.array(i) #取出一组值
    for j in temp1:
        b=np.array(j)    #取出一组值
        tp=tanimoto(a,b)
        tmp.append(tp)
    temp.append(tmp)
Tanimoto=pd.DataFrame(temp,columns=index_l,index=index_l)
# 获取栏目数组
ttpp = []
for i in list(Tanimoto.columns):
    ttpp.append(str(i)[1:-1])
data2 = pd.DataFrame(data2.iloc[:,2:].T.values, columns=list(ttpp))
columns = data2.columns
# 删去对应行后的字典
dict_lines = {}
count = 0
ct = 0
for i in Tanimoto.index:
    y = list(Tanimoto.iloc[:,ct])
    y.pop(count)
    count += 1
    dict_lines[columns[ct]] = y
    ct += 1
# 分离x y数据构造字典
dict_columns = {}
for i in columns: 
    
    # b
    y = data2.loc[:,i]
    
    # A
    temp = []
    for j in columns:
        if j != i:
            temp.append(j)
    m = data2.loc[:, temp[0]]
    tp = [m]
    for j in temp[1:]:
        tp.append(data2.loc[:, j])
    x = pd.DataFrame(tp).T
    

    tp = []
    for j in columns:
        if i != j:
            tp.append(j)
    df = pd.DataFrame(dict_lines[i], index=tp)
    df.sort_values(by=0 , inplace=True, ascending=True)
    max_l = df.index[-5:]
    tp = []
    for j in max_l:
        tp.append(data2.loc[:, j])
    max_5x = pd.DataFrame(tp).T
    
    # 存储
    data = {
        "x": x,
        "y": y,
        "max_relevance": max_l,
        "max_5x": max_5x
    }
    dict_columns[i] = data
# 删去对应行后的字典
dict_high_lines = {}
count = 0
cct = 0
for i in Tanimoto.index:
    y = list(Tanimoto.iloc[:,cct])
    y.pop(count)
    count += 1
    dict_high_lines[str(i)[1:-1]] = y

    tp = []
    for j in columns:
        if str(i)[1:-1] != j:
            tp.append(j)
    df = pd.DataFrame(dict_high_lines[str(i)[1:-1]], index=tp)
    df.sort_values(by=0 , inplace=True, ascending=True)

    max_l = df.index[-5:] 
    tp = []
    for j in max_l:
        tp.append(Tanimoto.iloc[list(columns).index(j), :])
    max_5y = list(pd.DataFrame(tp).T.iloc[[list(columns).index(str(i)[1:-1])]].values)[0]

    data = {
        "y": y,
        "max_relevance": max_l,
        "high_5": max_5y
    }
    dict_high_lines[str(i)[1:-1]] = data
    cct += 1

drug_dict_columns=dict_columns
drug_dict_high_lines=dict_high_lines

In [3]:
def dictW_C(alpha):
    # 运算构造参数W字典 
    dict_W = {}
    count = 0
    for elem in cell_dict_high_lines:
        r = np.array(cell_dict_high_lines[elem]["high_5"])
        W1= pow((1-r),2)
        W = np.exp(-W1/(2*pow(alpha[count],2)))
        dict_W[elem] = W
        count+=1
    return dict_W

def dictW_D(alpha):
    # 运算构造参数W字典 
    dict_W = {}
    count = 0
    for elem in drug_dict_high_lines:
        r = np.array(drug_dict_high_lines[elem]["high_5"])
        W1= pow((1-r),2)
        W = np.exp(-W1/(2*pow(alpha[count],2)))
        dict_W[elem] = W
        count+=1
    return dict_W

def dictr(dict_W):
    # 均方误差字典 （MSE=
    # r = max(|A×W - b|)
    dict_r = {}
    for elem,w in zip(dict_columns, dict_W):
        A = np.array(dict_columns[elem]["max_5x"].values) # x----->max_5x
        b = np.array(dict_columns[elem]["y"].values)
        W = dict_W[w]
        temp1 = np.dot(A,W) - b
        temp2 = np.square(temp1)
        temp3 = np.mean(temp2)
        dict_r[w] = temp3
    return dict_r

def dirlist(dict_r):
    #计算误差平方和    
    dir_list = []
    for elem in dict_r:
        dir_list.append(np.sqrt(dict_r[elem]))
    return dir_list

In [3]:
import pickle

with open('细胞系alpha.pkl', 'rb') as file:
    cell_dict_alpha = pickle.load(file)

EOFError: Ran out of input

In [2]:
import pickle

with open('药物对alpha.pkl', 'rb') as file:
    drug_dict_alpha = pickle.load(file)

In [4]:
max(drug_dict_alpha)

0.06326530612244897

In [6]:
cell_alp=[0.1 for i in range(35)]
drug_alp=[0.1 for i in range(583)]
cell_alp_copy=cell_alp
drug_alp_copy=drug_alp

In [20]:
cell_dict_W = dictW_C(drug_dict_alpha)
drug_dict_W = dictW_D(cell_dict_alpha)

data1 = pd.read_excel(r'pcbi.1006752.s002.xlsx', sheet_name="Sheet1",index_col='Drug').drop('SMILES',axis=1)
data2 = pd.read_excel(r'Label_synergy4000.xlsx')
data2_columns = data2.columns[2:]

# 结构  {名字： 名字列表， 权重： 权重列表} 顺序对应
dict_molecule_cell = {}
for elem in cell_dict_high_lines:
    dict_molecule_cell[elem] = []
    dict_molecule_cell[elem].append(cell_dict_columns[elem]["max_relevance"][-13:])
    dict_molecule_cell[elem].append(cell_dict_W[elem][-13:])

dict_molecule_drug = {}
for elem in drug_dict_high_lines:
    dict_molecule_drug[elem] = []
    dict_molecule_drug[elem].append(drug_dict_columns[elem]["max_relevance"][-5:])
    dict_molecule_drug[elem].append(drug_dict_W[elem][-5:])

# 拆分索引获取每行对应的drugA和drugB
drugA = []
drugB = []
for i in dict_molecule_drug:
    drugA.append(i.split(", ")[0][1:-1])
    drugB.append(i.split(", ")[1][1:-1])

data22=data2

# 获取得分高的细胞系名称组
cells = []
for i in dict_molecule_cell:
    cells.append(i)
cells.extend(data22.columns[0:2])


# 从原始数据中按列取得分高的细胞系
temp = []
for column,line in data22.iteritems():
    if column in cells:
        temp.append(line)
data222 = pd.DataFrame(temp).T

# 筛选结果合并drugA和drugB
tptt = []
for i,j in zip(data222['DrugA'], data222['DrugB']):
    tptt.append(f"'{i}', '{j}'")
data222 = pd.DataFrame(data222.iloc[:,2:].values,index=tptt,columns=data222.columns[2:])


# 原始数据合并drugA和drugB
tptt = []
for i,j in zip(data2['DrugA'], data2['DrugB']):
    tptt.append(f"'{i}', '{j}'")
data3 = pd.DataFrame(data2.iloc[:,2:].values,index=tptt,columns=data2.columns[2:])
data2 = data3.copy()

# 预测筛选后的药物对与细胞系的协同得分
result_df = []
for i in data222.index:
    tp = []
    for k in data222.columns[0:]:
        molecule = 0
        denominator = 0
        a = dict_molecule_cell[k][0]
        b = dict_molecule_drug[i][0]
        cw = dict_molecule_cell[k][1]
        dw = dict_molecule_drug[i][1]
        for m,ccw in zip(a,cw): # 细胞系   名字  权重
            for n,ddw in zip(b,dw): # 药物对   名字   权重
                # 分子子项 = 细胞系权重 × data2对应名字的值 ×药物对权重
                temp_molecule = ccw*data2[data2.index==n][m].values[0]*ddw
                # 分母子项 = 细胞系权重 × 药物对权重
                #temp_denominator = ccw*ddw
                temp_denominator=1
                molecule += temp_molecule
                denominator += temp_denominator
        result = molecule / denominator
        tp.append(result)
    result_df.append(tp)

sens=pd.DataFrame(np.array(result_df),index = data222.index, columns=data222.columns)

MSE=pow(data222-sens,2).sum().sum()/(sens.shape[0]*sens.shape[1])

MSE

526.5190606520167

In [14]:
dict_molecule_cell

{'A2058_SKIN ': [Index(['RPMI7951_SKIN ', 'COLO320_LARGE_INTESTINE ', 'MSTO211H_PLEURA ',
         'HT29_LARGE_INTESTINE ', 'NCIH1650_LUNG ', 'SW620_LARGE_INTESTINE ',
         'CAOV3_OVARY ', 'A2780_OVARY ', 'MDAMB436_BREAST ', 'HT144_SKIN ',
         'SKMEL30_SKIN ', 'UACC62_SKIN ', 'NCIH460_LUNG '],
        dtype='object'),
  array([0.45370533, 0.51174746, 0.52629189, 0.56598286, 0.60980863])],
 'A2780_OVARY ': [Index(['HT29_LARGE_INTESTINE ', 'A427_LUNG ', 'OVCAR4_OVARY ',
         'MDAMB436_BREAST ', 'SKMEL30_SKIN ', 'NCIH460_LUNG ',
         'SW837_LARGE_INTESTINE ', 'LOVO_LARGE_INTESTINE ', 'CAOV3_OVARY ',
         'SW620_LARGE_INTESTINE ', 'A2058_SKIN ', 'VCAP_PROSTATE ',
         'COLO320_LARGE_INTESTINE '],
        dtype='object'),
  array([0.53409692, 0.53856768, 0.55295517, 0.69884354, 0.84360473])],
 'A375_SKIN ': [Index(['CAOV3_OVARY ', 'HCT116_LARGE_INTESTINE ', 'HT29_LARGE_INTESTINE ',
         'NCIH520_LUNG ', 'LOVO_LARGE_INTESTINE ', 'SKMEL30_SKIN ',
         'ZR751_B

In [8]:
ccw

0.11709416665665782

In [13]:
cw

array([0.01152471, 0.01243092, 0.01388881, 0.0210057 , 0.11709417])

In [12]:
data2

A2058_SKIN   A2780_OVARY   A375_SKIN   \
'MK-5108', 'SORAFENIB'                   -9.510       2.60000      15.200   
'VINORELBINE', 'SUNITINIB'              -13.200      -4.03000      11.100   
'SUNITINIB', 'MK-8776'                   26.400      14.50000      29.500   
'5-FU', 'DINACICLIB'                      4.330      -8.16000      -5.420   
'SUNITINIB', 'MK-2206'                   45.500      22.50000      22.800   
'PACLITAXEL', 'BEZ-235'                  -5.010      -3.86000      25.500   
'MK-2206', 'DINACICLIB'                   9.970       1.69000      13.200   
'MK-4827', 'MK-8776'                     76.200      21.60000      38.700   
'VINORELBINE', 'DINACICLIB'             -16.000     -19.20000    -123.000   
'MK-5108', 'MK-8776'                     -4.970      11.10000       8.950   
'TEMOZOLOMIDE', 'SN-38'                   8.480       3.41000      -5.000   
'ETOPOSIDE', 'MK-8669'                   -4.100      22.70000      30.700   
'SUNITINIB', 'MK-4827'                   -4.390      -0.99500       6.120   
'BORTEZOMIB', 'GELDANAMYCIN'            -12.300     -17.00000       9.450   
'PACLITAXEL', 'ABT-888'                  -4.810      -4.34000      13.100   
'CYCLOPHOSPHAMIDE', 'BEZ-235'            12.700      17.90000      12.800   
'DASATINIB', 'DINACICLIB'                48.900      29.20000       1.850   
'METHOTREXATE', 'ERLOTINIB'              -7.980      -3.94000      22.900   
'MK-2206', 'TOPOTECAN'                    9.800      17.20000      20.800   
'AZD1775', 'MK-4827'                     32.800       9.07000      20.400   
'METFORMIN', 'BEZ-235'                   28.200      19.90000      14.400   
'ZOLINZA', 'AZD1775'                     -5.770       3.19000      21.000   
'DASATINIB', 'SORAFENIB'                 36.300      26.20000      29.900   
'CYCLOPHOSPHAMIDE', 'TEMOZOLOMIDE'       18.100       9.30000      12.100   
'MRK-003', 'PACLITAXEL'                  10.800      15.50000      61.200   
'DEXAMETHASONE', 'LAPATINIB'            -16.200       0.36800      -5.110   
'DEXAMETHASONE', 'MK-8669'               10.700       1.43000      12.400   
'ERLOTINIB', 'BEZ-235'                   30.400      33.00000      32.800   
'VINBLASTINE', 'PD325901'                14.200      10.90000      -1.730   
'MK-4541', 'METFORMIN'                    4.370       0.50700      -8.610   
...                                         ...           ...         ...   
'ETOPOSIDE', 'MK-2206'                   23.800      25.10000      40.400   
'ETOPOSIDE', 'MK-4827'                   -1.380       8.88000       6.250   
'LAPATINIB', 'MK-4827'                   17.400      14.40000      14.100   
'MRK-003', 'ERLOTINIB'                    4.340       9.29000       9.070   
'ERLOTINIB', 'DASATINIB'                 50.900      55.70000       4.770   
'PACLITAXEL', 'GELDANAMYCIN'            -29.000     -16.80000      -4.070   
'5-FU', 'L778123'                         9.730       8.79000       7.630   
'ERLOTINIB', 'MK-8776'                   24.100      29.20000      37.700   
'MITOMYCINE', 'L778123'                 -11.500      -5.12000      -8.500   
'AZD1775', 'MK-8669'                     38.900      26.20000      42.600   
'L778123', 'LAPATINIB'                   15.600      15.90000      21.200   
'MRK-003', 'AZD1775'                     10.200       6.60000       8.470   
'MK-4541', 'CYCLOPHOSPHAMIDE'             0.865       3.98000       4.090   
'ETOPOSIDE', 'MK-8776'                   57.700      21.30000     -65.100   
'METFORMIN', 'MK-4827'                   10.700       9.11000       1.580   
'CYCLOPHOSPHAMIDE', 'ERLOTINIB'          -2.480      -0.00997      -4.230   
'ZOLINZA', 'MK-2206'                     11.200       1.19000       7.320   
'VINBLASTINE', 'MK-8669'                 50.500       7.88000       6.250   
'PD325901', 'OXALIPLATIN'                 4.640       7.66000     -13.800   
'MK-4541', '5-FU'                         2.480       3.62000       2.080   
'BORTEZOMIB', 'TOPOTECAN'       